.github/workflows/sanity-test.yml
konflux-ci/ui/README.md
konflux-ci/ui/core/chrome/chrome-frontend.yaml
konflux-ci/ui/core/chrome/kustomization.yaml
konflux-ci/ui/core/fed-modules.json
konflux-ci/ui/core/hac/hac-core-frontend.yaml
konflux-ci/ui/core/hac/hac-dev.yaml
konflux-ci/ui/core/hac/kustomization.yaml
konflux-ci/ui/core/kustomization.yaml
konflux-ci/ui/core/ns.yaml
konflux-ci/ui/core/proxy/kustomization.yaml
konflux-ci/ui/core/proxy/nginx.conf
konflux-ci/ui/core/proxy/proxy.yaml
konflux-ci/ui/kustomization.yaml

Right now it's still not usable since it needs a keycloak endpoint for providing authentication and kubesaw / alternative routing for communicating with the api server and registering users.

Deploy the UI

---

konflux-ci/ui/core/proxy/proxy.yaml

The amount of bytes to remove from the service account is different when using long lived tokens.

Fix service account parsing

---

konflux-ci/ui/core/proxy/nginx.conf
konflux-ci/ui/core/proxy/proxy.yaml
test/resources/demo-users/demo-users.yaml

1. Authenticate requests using oauth2-proxy (currently configured to use Keycloak since this is what our UI is using).
2. Since oauth2-proxy doesn't know how to parse the "Sec-Websocket-Protocol" header, transform the header to a standard bearer token using a lua function.
3. In order to use lua (which provides the base64 decode method), the ubi nginx image was changed to an openresty image. It provides nginx with the support of lua.
4. The change to the openresty image required some change to the deployment manifest of nginx.
5. Use the email address information of the logged user, as returned from oauth2-proxy for impersonation, registration and workspace listing.
6. Print nginx error log to STDERR for better debugging.
openresty:
- https://github.com/openresty/docker-openresty
- …

Adding Authentication

---

.github/workflows/sanity-test.yml
dependencies/keycloak/crd/kustomization.yml
dependencies/keycloak/deployment/configure-keycloak.yaml
dependencies/keycloak/deployment/db.yaml
dependencies/keycloak/deployment/kustomization.yml
dependencies/keycloak/deployment/ns.yaml
deploy-deps.sh
deploy-konflux.sh
konflux-ci/ui/core/fed-modules.json
konflux-ci/ui/core/proxy/nginx.conf
konflux-ci/ui/core/proxy/proxy.yaml
wait-for-all.sh

It will be used as the IDP. It's configured with 2 test users by defualt, but it can also integrate with external IDPs such as Github, Google, etc. The port nginx uses for https was changed to match the port which is used to forward traffic from the host. It's required since oauth2-proxy expects them to be the same (when it queries the details of the realm from keycloak).
The endpoints are exposed through the nginx proxy.
The documentation used for creating this patch:
- https://www.keycloak.org/operator/basic-deployment
- https://www.keycloak.org/server/reverseproxy https://stackoverflow.com/questions/66822016/where-are-all-of-the-keycloak-protocol-mapper-config-options-documented

Deploy Keycloak

---

test/resources/demo-users/user/ns2/rbac.yaml

Adding RoleBinding to allow user1 access to user2's workspace in order to demonstrate user access to multiple workspaces.

chore(RHTAPWATCH-1006): allow user1 access to ws2

---

README.md
kind-config.yaml

The system, at least on Podman, was not stable during startup and when triggering pipelines.
This change is includes reserving memory for the cluster by default and provides a command for increasing the PID limit.

chore: reserve memory and increase pid-limit

---

deploy-deps.sh

We should use kubectl instead of create, so that the script could be executed multiple times.
closes #72

fix: use kubectl apply when deploying registry

---

README.md
test/resources/demo-users/user/ns2/ec-integration-test.yaml

This change explains how to add integration tests. The pipeline used does not support custom certificates at the moment, so this change also covers moving from the local registry to a public one.

doc: add integration tests

---

README.md

The build pipeline in testrepo now has the git url parameterized. A change in the README here is required to reflect that.
Closes: #81

doc: use parameterized repo url in build pipeline

---

.github/workflows/check-toc.yaml
CONTRIBUTING.md
README.md

This PR introduces markers on the README file for table of contents to be used by an application to generate it, alongside an action that checks whether it is up to date or not. CI will prompt the user to run the command if the table of contents is out dated.

chore: add README table of contents

---

README.md

I hit an issue where individual deployments would be stuck in `./wait-for-all.sh`, even though the cluster itself was up.

doc: hint to the user that file descriptor limit may apply to deployments

---

README.md
dependencies/pre-deployment-pvc-binding/kustomization.yml
dependencies/pre-deployment-pvc-binding/pre-deployment-pvc-binding.yaml
deploy-deps.sh

Adding a check in deploy-deps to ensure PVCs are bound and the cluster has default storage cluster, before deploying all the resources.
fix #58

chore(RHTAPWATCH-1018): test PVC creation pre-deployment

---

README.md
deploy-deps.sh

The retry format was changed, but the procedure for deploying a test PVC is still using the old format. This change addresses that.

fix: test pvc use old retry format

---

konflux-ci/build-service/build-pipeline-config.yaml
konflux-ci/build-service/core/apps_v1_deployment_build-service-controller-manager.yaml
konflux-ci/build-service/kustomization.yaml
konflux-ci/ui/core/kustomization.yaml
test/resources/demo-users/user/ns1/application-and-component.yaml

Update hac-dev image
The new image has the new simple import form and several fixes
for the link to the documentation.
Update build-service image
The new image supports importing a component without a devfile and
selecting a pipeline by adding an annotation on the component.
See test/resources/demo-users/user/ns1/application-and-component.yaml
for an example.

Integrate the new import flow

---

README.md
dependencies/tekton-config/tekton-config.yml
test/resources/demo-users/user/ns2/appstudio-pipeline-sa.yaml
test/resources/demo-users/user/ns2/kustomization.yaml

Add service account to user-ns2
Update README
Update tektonconfig to use appstudio-pipeline as a default service account
fix #105

Use the "appstudio-pipeline" service account for running pipelines

---

dependencies/pipelines-as-code/custom-console-patch.yaml
dependencies/pipelines-as-code/kustomization.yml

This way, a user who clicks on their github check result will be directed to their their local instance's UI.
Fixes https://github.com/konflux-ci/konflux-ci/issues/97

feat: provide PaC links to the local console

---

konflux-ci/rbac/core/tekton-chains.yaml

Create the tekton-chains secret in openshift-pipelines namespace to work around a bug in which the UI looks for the secret on the wrong namespace.

chore: create tekton-chains secret in another temp ns

---

.github/workflows/check-toc.yaml
CONTRIBUTING.md
README.md
docs/github-secrets.md
docs/quay.md
docs/troubleshooting.md

Split the onboarding process to two options.
Move some of the common tasks to separate files to keep the README from exploding.
closes: #121 
closes: #125

doc(RHTAPWATCH-1049): onboard app through the UI

---

README.md

Move the reference to the troubleshooting section to an earlier point so that users will know it exists before trying to troubleshoot on their own.

doc: reference the troubleshooting section earlier

---

konflux-ci/build-service/build-pipeline-config.yaml
konflux-ci/build-service/core/appstudio.redhat.com_v1alpha1_buildpipelineselector_build-pipeline-selector.yaml
konflux-ci/enterprise-contract/core/enterprise-contract-service_appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_all.yaml
konflux-ci/enterprise-contract/core/enterprise-contract-service_appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_default.yaml
konflux-ci/enterprise-contract/core/enterprise-contract-service_appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_redhat-no-hermetic.yaml
konflux-ci/enterprise-contract/core/enterprise-contract-service_appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_redhat.yaml
konflux-ci/enterprise-contract/core/enterprise-contract-service_appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_slsa3.yaml
konflux-ci/rbac/core/tekton-chains.yaml
test/resources/demo-users/user/managed-ns1/ec-policy.yaml
test/resources/demo-users/user/managed-ns2/ec-policy.yaml

STONEBLD-2339
All the images built in build-definitions CI now get released to the
quay.io/konflux-ci organization.
Replace the relevant redhat-appstudio[-tekton-catalog] references in
this repo with konflux-ci[/tekton-catalog] references.
Signed-off-by: Adam Cmiel <acmiel@redhat.com>

Migrate build-definitions redhat-appstudio images

---

README.md

The component name was missing from the instructions for editing the RPA manifest. This change adds it.
closes: #135

doc: set component name in rpa manifest

---

.github/workflows/sanity-test.yml
.gitignore
generate-err-logs.sh

Adds a script which collects failed pods information using k8s events. This will be used to debug failed deployments, either from the CI or locally.
fix #17

chore(RHTAPWATCH-1046): collect failed deployment information

---

konflux-ci/release/core/release-service-config.yaml
test/resources/demo-users/user/managed-ns2/rpa.yaml

The name of the release service config resource that is expected during the release pipeline has changed. This change addresses that. We also move to using the upstream release pipeline as it is no longer needed to use a modified version of it.

fix: release service config name

---

README.md

Previously this password, although the same as for user1, was only listed later in the second option using CLI.

Add password for user2 in Onboard Application with the Konflux UI

---

dependencies/keycloak/deployment/configure-keycloak.yaml

There was bug where the user's first and last name were not visible in the UI since they weren't included in the JWT token. Include the "first_name" and "last_name" claims in the JWT token.

Show the user's first and last name on the UI

---

README.md

The user can potentially create the application on user-ns1, so adding instructions for verifying the namespace.
closes #155

doc: verify correct workspace selected

---

.mise.toml

Using [mise][1] to setup kind and kubectl.
[1]: https://mise.jdx.dev/

Add mise configuration for tool autmation

---

generate-err-logs.sh

The generate-err-logs is used to help us debug failures within the cluster.
We encountered an issue where one of the namespaces failed the script due to its pod missing the logs that are being read by the script.
Instead of failing, the script will skip the failure and log the inability to access this resource.
In order to debug such situations better, added a print describing which namespace's output is currently showing.

chore: handle errors on generate-err-logs.sh

---

dependencies/keycloak/deployment/db.yaml

It shouldn't use a load balancer since it shouldn't be accessed from outside of the cluster.

Use ClusterIP service for keycloak's DB

---

.github/workflows/sanity-test.yml

ensures the `Generate error logs` step executes even, even if some of the tasks fail.

chore: ensure logs are generated on task failure

---

README.md
docs/troubleshooting.md

If quay setup is skipped, the user will encounter a 404 Not Found error when trying to create an application. This change documents that.
closes: #150

docs: 404 Not Found when creating application

---

README.md

We mention that the user should increase the inotify resources only in case they encounter failures due to too many open files.
We know that the user will most likely need it increased, and figuring out the issue on a later stage might be challenging and frustrating.
To avoid that, we should recommend that the user will increase the limit sooner rather than later.

doc: strongly suggest increasing inotify resources

---

README.md

Users mentioned they are unable to deploy on ARM macos, so we should specify that we only support x86_64 Linux at the moment.

doc: list supported platform

---

dependencies/pre-deployment-pvc-binding/pre-deployment-pvc-binding.yaml

Explicitly create the default service account for the namespace in which the test PVC is created. This is to avoid cases when it takes too long for that service account to be created, causing creating of the test pod to fail, requiring the user to run deploy-deps again.
closes: #161

fix: explicitly create default sa for test pvc

---

dependencies/pre-deployment-pvc-binding/pre-deployment-pvc-binding.yaml

There was a bug in which the default service account was sometimes created too late when testing creation of PVC. To address that, we're now creating the SA explicitly.
Having said that, there's still seem to be a race condition between the time the SA is created automatically and explicitly, which now causes the opposite error: serviceaccounts "default" already exists.
closes: #206

fix: undo adding of default service account

---

konflux-ci/build-service/core/kustomization.yaml

A PR with misconfigurations created by renovate was accidentally merged. This fixes those misconfigurations.

fix: manually set build-service tag

---

renovate.json

By explicitly setting the "packageNameTemplate" its value will be used for each dependency matched using the match strings.

renovate: Mention packageNameTemplate

---

renovate.json

A single manager can't update both the reference to the manifests and image in the kustomization file.

Renovate add manager

---

test/resources/demo-users/user/managed-ns1/rpa.yaml
test/resources/demo-users/user/ns1/build-pipeline.yaml
test/resources/demo-users/user/ns1/ec-integration-test.yaml
test/resources/demo-users/user/ns2/ec-integration-test.yaml

- Remove private git repositories
- fix [#53](https://github.com/konflux-ci/konflux-ci/issues/53)

fix(RHTAPWATCH-1042): Remove mentions of private repos (git, quay) from all namespace files (e.g. ns1)

---

konflux-ci/release/core/kustomization.yaml
konflux-ci/release/internal-services/kustomization.yaml
konflux-ci/release/kustomization.yaml

This change will allow renovate to properly update the core release service kustomization file.

Move internal services to its own kustomization

---

docs/troubleshooting.md

If webhook secret was not added in the github application the PR created fails the pipeline check.
closes: #212

docs: webhook secret error in the PR

---

konflux-ci/rbac/core/tekton-chains.yaml

Configuring the job to run as non-root caused it to fail to start. Setting a specific user should address this.
closes: #240

fix: tekton-chains job fails to start

---

dependencies/cert-manager/self-signed-cluster-issuer.yaml
dependencies/registry/certificate.yaml
dependencies/registry/kustomization.yml
dependencies/registry/registry.yaml

This will eventually be used for allowing a flow that uses the internal registry instead of quay.io, which should be easier to follow.
Note: this PR is opened toward a feature branch (not main). It can potentially break the e2e flow. The e2e flow will be verified before this is merged to main.

add self-signed certificate to local registry

---

dependencies/registry/trust-bundle.yaml
dependencies/trust-manager/kustomization.yml
dependencies/trust-manager/trust-manager.yaml
deploy-deps.sh

Copy the local registry certificate to the cert-manager namespace and use trust-manager to distribute to all namespaces a CA bundle containing a default CA together with the registry's custom CA as configmaps.
Tasks will later on mount those configmaps to allow them to use the self-signed certificate.

distribute registry ca certificate

---

README.md

The registry now uses https and the documentation should reflect that.

doc: curl registry over https

---

.github/workflows/sanity-test.yml
CONTRIBUTING.md
test/e2e/customize-docker-pipeline.sh
test/e2e/prepare-e2e.sh
test/e2e/run-e2e.sh
test/e2e/vars.sh

Add e2e test for validating the build->integration-test->release scenario (similar to the one described in the [readme of this repo](https://github.com/konflux-ci/konflux-ci?tab=readme-ov-file#onboard-a-new-application))
The test is using https://github.com/konflux-ci/testrepo as a component repository and this GitHub app: https://github.com/apps/konflux-ci-test-app
There are currently [issues with running `clair-scan` task in github actions](https://github.com/konflux-ci/konflux-ci/issues/241) (see comments below for more info). The task just hangs in `Running` state until it times out (after 1h). Due to that I introduced a workaround to temporarily remove this task from the build pipeline.
* ~after rebase the test is failing on `"couldn't get the secret public-key from …

feat: e2e test

---

.github/workflows/sanity-test.yml

run if:
* a PR author is a member of the organization
* or a PR author is "renovate[bot]"
* or a PR contains "ok-to-test" label
closes https://github.com/konflux-ci/konflux-ci/issues/254
PR for testing org membership: https://github.com/psturc-org/konflux-ci/pull/7
PR for testing "ok-to-test" label presence: https://github.com/psturc-org/konflux-ci/pull/8

feat: rewrite conditions for running sanity test

---

dependencies/tekton-config/tekton-config.yml

Tekton chains needs access to the custom CA. Otherwise, no attestations are pushed to the registry.

feat(RHTAPWATCH-1191): Mount custom CA bundle to tekton chains

---

dependencies/cluster-issuer/self-signed-cluster-issuer.yaml
dependencies/registry/certificate.yaml
dependencies/registry/trust-bundle.yaml
deploy-deps.sh

Distribute the root certificate and use it for creating the registry's own certificate, rather than using the root cluster issuer for creating the registry certificate.
This allows us to avoid copying the certificate's secret from the registry namespace to the cert-manager namespace for distribution.

chore(RHTAPWATCH-1184): distribute root certificate

---

test/resources/demo-users/user/ns2/ec-integration-test.yaml

The EC integration test task was updated and now supports mounting custom CA certificate. The EC pipeline was updated to point to the updated task. This change references the updated pipeline.

feat: ec pipeline support custom cert

---

konflux-ci/ui/core/proxy/proxy.yaml

1. For 30 seconds, check if no containers in the pod crash loop and only then declare that the pod ready.
2. Add readiness probe. Traffic will be forwarded only to pods that pass the readiness check.
3. Adjust probes to start only after 30 seconds to match the change mention in 1.
4. Don't allow the deployment to have less than the desired replica count, even during upgrade.

Improve nginx deployment

---

dependencies/tekton-config/tekton-config.yml

We were mounting the CA bundle to /etc/ssl/certs/ca-custom-bundle.crt, but this file was ignored. Trying to find an alternative which adds a single file instead of overwriting the content of the entire /etc/ssl/certs dir did not work.
So, this change overrides the entire content of the /etc/ssl/certs dir. As the bundle that we're mounting also contains the default CA certs, this should not be an issue.
The current setup was tested against both local registry and quay, and confirmed work with both.

fix: custom ca cert not picked

---

.github/.kube-linter-config.yaml
dependencies/cert-manager/kustomization.yml
dependencies/keycloak/deployment/db.yaml
dependencies/keycloak/deployment/kustomization.yml
dependencies/pipelines-as-code/kustomization.yml
dependencies/pre-deployment-pvc-binding/pre-deployment-pvc-binding.yaml
dependencies/registry/registry.yaml
dependencies/tekton-operator/kustomization.yml
dependencies/tekton-results/kustomization.yml

Allocating resources to solve Kubelinter's resource allocation issues.
I tested those changed during and after all changes were made, I was also able to release using my local Konflux-ci.
**Resource allocation tests and results:**
**dependencies/cert-manager/Kustomization.yml + dependencies/keycloak/deployment/db.yaml:**
Raised all cpu and memory requests from 10m to 90m and from 10Mi to 90Mi accordingly.
Tests tried : 30m,30Mi - build-container step failed from insufficient resources, same happened for 50. for 80 and 85 build-container passed but the next steps were flaky and each time different step failed because of lacking resources.
**dependencies/keycloak/deployment/kustomization.yml:**
cpu and memory set to 50
**dependencies/pipelines-as-code/kustomization.yml:**
cpu and memory set …

chore(RHTAPWATCH-1110): solve KubeLinter's resource allocation issues

---

konflux-ci/build-service/core/kustomization.yaml
konflux-ci/build-service/core/mount-custom-ca-bundle.yaml
test/e2e/customize-docker-pipeline.sh
test/e2e/vars.sh
test/resources/demo-users/user/managed-ns2/appstudio-pipeline-sa.yaml
test/resources/demo-users/user/ns2/appstudio-pipeline-sa.yaml

The dockerconfigjson file that is used by some of the pipelines to hold info for authentication with the registry is still needed even though the registry is not using any authentication.
With this change, we introduce a dummy secret that allows this file to be created without any authentication info.

chore(RHTAPWATCH-1182): create secret for local registry

---

docs/troubleshooting.md

Triggered pipeline may be stuck for longer time. On checking the pod status on the user namespace. The pod will be in pending state.
This pr includes the pending pods describe output error message and how to reuse the instructions to fix it.
Closes: https://github.com/konflux-ci/konflux-ci/issues/281

Added FailedScheduling symptom for pending pod to the troubeshotting doc

---

dependencies/trust-manager/trust-manager.yaml

Trust-manager deployment was missing resource limits and requests. This change adds those.

chore: add resource specs to trust-manager

---

konflux-ci/ui/core/proxy/proxy.yaml

Use proper released images for workspace-manager instead of the dev image that was used up until now.

chore(RHTAPWATCH-1076): use released workspace-manager images

---

renovate.json

Update renovate configs so they update the ec-task-bundle image
and git ref used in the ec controller configs.
https://github.com/konflux-ci/konflux-ci/blob/d1d7260d49e7245ce53503e81f39537b5a8c50bb/konflux-ci/enterprise-contract/core/kustomization.yaml#L16-L18

chore: use renovate to maintain ec configmap

---

.github/workflows/sanity-test.yml

Temporarily using non-latest ubuntu runner as the latest runner is causing a regression.

fix: use ubuntu-22.04

---

.github/workflows/sanity-test.yml

The ubuntu-latest GitHub runner was updated to 24.04. In that version unprivileged user namespaces have more restrictions and this interferes with our Kind deployment. To avoid that, we disable AppArmor on the runner.
https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces
Closes #530

fix: disable AppArmor

---

README.md

The README specifically mentions an external registry when configuring releases. This is no longer the case, and the internal registry can be used for releases as well.
closes: #601

docs: release to external or internal registry

---

konflux-ci/image-controller/core/kustomization.yaml
konflux-ci/image-controller/core/replace-pruner-image.yaml

The image-controller configs that we use references an image that requires authentication. This change patches the relevant manifest so it uses an image that does not require authentication.
closes: #573

chore: use public image for image-controller pruner job

---

konflux-ci/release/core/kustomization.yaml
test/resources/demo-users/user/ns1/release-plan.yaml

For local releases, pipeline was renamed to tenantPipeline. This need to be reflected in our configs to be able to update release-service.
Closes: #631

fix: rename pipeline to tenantPipeline

---

konflux-ci/ui/core/kustomization.yaml

Update hac-dev to address a regression in the UI that caused releases to be stuck with status pending instead of moving to status Succeeded.
Closes: #602

fix(KFLUXBUGS-1793): release stuck in pending

---

konflux-ci/ui/core/proxy/proxy.yaml

For websockets the token should be processed in a certain way before sending it to the k8s API. It should be based64 encoded without padding [1].
The current implementation assumed a padding of 1 char, but it was seen that it can be 2 chars. Adjust the processing to remove any padding from the token.
[1] - https://github.com/kubernetes/kubernetes/pull/47740

Better token handling for websockets

---

konflux-ci/ui/core/kustomization.yaml
konflux-ci/ui/core/proxy/nginx.conf
konflux-ci/ui/core/proxy/proxy.yaml

kubernetes/kubernetes#47740 was misunderstood.
it was implemented to support authentication from a web browser.
Since we have a proxy, it can include the Authorization bearer token,
so no special header is needed for websocket authentication.

Authorization bearer token for websockets - new UI

---

konflux-ci/ui/core/proxy/nginx.conf
konflux-ci/ui/core/proxy/proxy.yaml

https://github.com/kubernetes/kubernetes/pull/47740 was misunderstood. it was implemented to support authentication from a web browser. Since we have a proxy, it can include the Authorization bearer token, so no special header is needed for websocket authentication.
Since the UI already includes the "Sec-Websocket-Protocol" with a token, it should be redefined (in the new UI this won't be needed).

Authorization bearer token for websockets

---

konflux-ci/ui/core/proxy/nginx.conf
konflux-ci/ui/core/proxy/proxy.yaml
renovate.json

Use UBI nginx image
With the old UI we needed to use OpenResty since it has LUA
features that we needed for parsing the JWT token.
This isn't the case anymore with the new UI, so we can use UBI
nginx instead.
Enable renovate for Redhat public registry
Enable renovate for pulling updates from
registry.access.redhat.com.

Use UBI nginx image and enable update for Redhat images

---

konflux-ci/ui/core/proxy/kustomization.yaml
konflux-ci/ui/core/proxy/nginx.conf
konflux-ci/ui/core/proxy/proxy.yaml

It's possible to deploy Konflux without using impersonation for the proxy if the proxy and the cluster use the same IDP.
Allow this case by making impersonation optional.

Make impersonation optional

---

konflux-ci/ui/core/proxy/kustomization.yaml
konflux-ci/ui/core/proxy/nginx.conf
konflux-ci/ui/core/proxy/proxy.yaml

Tekton results URL may differ between installations.
Allow to configure it using a configmap.
depends on https://github.com/konflux-ci/konflux-ci/pull/831

Allow to configure tekton-results URL 

---

konflux-ci/build-service/core/build-pipeline-config.yaml

The UI already has it hardcoded as the default.
Before this change, user usage would fail since the UI tries to request this pipeline, but it doesn't exist in build-service's configmap.

Make docker-build-oci-ta the default pipeline

---

README.md

With the new UI we need to use emails to login rather than usernames. This change fixes a couple of places in which it was not documented properly.

fix: use email to login

---

.github/workflows/kube-linter.yaml
.gitignore
README.md
dependencies/smee/kustomization.yml
dependencies/smee/smee-channel-id.tpl
dependencies/smee/smee-client.yaml
deploy-deps.sh
test/e2e/prepare-e2e.sh

Randomize the smee channel ID and create the client providing that ID. The ID is stored in a kustomize patch file (ignored by git). The channel will not be created if the patch already exists, so users can store their pre-existing channels in the patch and keep using them.
closes: #169

feat(KFLUXVNGD-3): automate smee channel creation

---

.github/workflows/sanity-test.yml
dependencies/dex/config.yaml
konflux-ci/ui/core/proxy/proxy.yaml
test/go-tests/proxy_suite_test.go

add a placeholder in actions for go proxy tests:
- Add a dummy test in go as a placeholder to proxy tests
- Update some parameters we need for the tests

add go proxy test placeholder

---

deploy-deps.sh
test/go-tests/proxy_test.go

Test suite will sometimes fail after fetching the token as it appears to be empty. This is caused by failed authentication, which seems to be related to a inconsistently-escaped characters when Dex is comparing the client secret.
To address this, we remove the characters that should cause such inconsistencies.

fix: flaky proxy test

---

.github/workflows/sanity-test.yml
test/e2e/customize-docker-pipeline.sh

clair-scan Task is not an issue anymore for github actions
closes https://github.com/konflux-ci/konflux-ci/issues/241

fix: remove workaround for clair-scan Task

---

dependencies/tekton-config/tekton-config.yml

See https://tekton.dev/docs/chains/config/#pipelinerun-configuration
Certain enterprise contract rules depend on this, in particular for deployments that have multi-arch builds enabled. There, we need the provenance associated not just with the final image index but also with all per-arch image manifests.

Enable tekton chains deep inspection

---

README.md

Reference Dex and oauth2-proxy instead of keycloak

docs: remove mentions of keycloak

---

konflux-ci/namespace-lister/kustomization.yaml
konflux-ci/namespace-lister/network_policy_allow_from_konfluxui.yaml
konflux-ci/namespace-lister/network_policy_allow_to_apiserver.yaml

this change allows the namespace-lister to only reach-out to the kube-apiserver

nslister: add egress NetworkPolicy

---

konflux-ci/namespace-lister/deployment.yaml

Add healthz and readyz probe checks into the namespace-lister deployment, so kubernetes has an idea of when pods are healthy and available to respond to requests.

namespace-lister: add healthz and readyz probes

---

deploy-konflux.sh
konflux-ci/build-service/core/build-service-env-patch.yaml
konflux-ci/build-service/core/kustomization.yaml

This PR adds a `kubectl` command to set the `PAC_WEBHOOK_URL` for the `build-service` so users can trigger builds directly from the UI. Currently if you try to trigger a build from the UI the `build-service` tries to reach for an OpenShift Route that does not exist, so this change is required.
PD: I'm not sure about the PR format, if any, let me know.

feat: add PAC_WEBHOOK_URL to allow UI builds

---

test/resources/demo-users/user/managed-ns1/rpa.yaml
test/resources/demo-users/user/managed-ns2/rpa.yaml

This PR changes the revision specified for the pipelines on the example ReleasePlanAdmissions because the SHA specified is not on the repository. See https://github.com/konflux-ci/release-service-catalog/commit/b0586bdee6e5721d773f4b5be6ca8cd8f70ddd32 and the warning at the top. The current SHA references a fix for a PR that is already merged, so I searched for the corresponding PR and used the SHA created by that PR when merged on their default branch.
cc @johnbieren @scoheb

Fix revision for Release Service repo

---

README.md

Update README with minimum required versions
kubectl: 1.31.1
Kind: 0.26.0
Close #1654

Update minimum kind and kubectl versions

---

dependencies/pipelines-as-code/kustomization.yml

The current PaC version is one year old and is missing some significant features.
Updating the version as part of stabilization of UI tests. https://issues.redhat.com/browse/KFLUXUI-338

update PaC version

---

dependencies/smee/smee-client.yaml

It seems Pod is on CrashLooping state, removing the livenessProbe recently added to come back to initial setup and look for a better solution of implementation in case is needed.

removing livenessProbe

---

dependencies/kyverno/policy/pod-requests-del.yaml

The policy will fail to be deployed if the pod it captures had some containers with resource requests undefined. This change should address that.

fix: kyverno policy for steps with undefined resources

---

dependencies/kyverno/kustomization.yaml
dependencies/kyverno/policy/e2e-reduce-resources.yaml
dependencies/kyverno/policy/pod-requests-del.yaml
test/e2e/customize-docker-pipeline.sh

Replace the script used for reducing task resources in CI with a kyverno policy.
This is an optimization attempt for [another PR](https://github.com/konflux-ci/konflux-ci/pull/1840).

chore: use kyverno for ci workaround - different logic

---

konflux-ci/build-service/core/build-config-rolebinding.yaml
konflux-ci/build-service/core/kustomization.yaml

Add a rolebinding to allow us to read from the build config map to create the list of available pipelines

chore(KONFLUX-7649): add rolebinding to read from build configmap

---

dependencies/smee/smee-client.yaml

We have created a new livenessProbe for smee-client, based on a simple echo "Service up" instead of choosing http check due to port forwarding issue.
Tracking ticket: https://issues.redhat.com/browse/SPRE-1255

Adding new livenessProbe to smee client

---

dependencies/smee/kustomization.yml
dependencies/smee/smee-client.yaml

This is required for allowing renovate to track gosmee updates.
Closes: #2134

chore: move gosmee image to kustomization file

---

konflux-ci/build-service/core/build-pipeline-runner-rolebinding.yaml
konflux-ci/build-service/core/kustomization.yaml

The Fedora cluster is missing the role binding for tying the appstudio-pipelines-runner cluster role to the build service service account.
This is meaningless in konflux-ci/konflux-ci, but is required when the build-service is deployed on an openshift cluster, such as the case of the Fedora cluster.

fix: add role binding for build service pipelines-runner

---

dependencies/smee/kustomization.yml
dependencies/smee/smee-channel-id.tpl
dependencies/smee/smee-client.yaml

This will track smee health and verify it's serving request.

chore(KFLUXVNGD-329): deploy smee sidecar

---

konflux-ci/enterprise-contract/policies/enterprise-contract-service_appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_all.yaml
konflux-ci/enterprise-contract/policies/enterprise-contract-service_appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_default.yaml
konflux-ci/enterprise-contract/policies/enterprise-contract-service_appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_redhat-no-hermetic.yaml
konflux-ci/enterprise-contract/policies/enterprise-contract-service_appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_redhat-trusted-tasks.yaml
konflux-ci/enterprise-contract/policies/enterprise-contract-service_appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_redhat.yaml
konflux-ci/enterprise-contract/policies/enterprise-contract-service_appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_slsa3.yaml

EC policies were not updated for almost a year
This PR updates them to the (currently) latest policies
Up next: automate updating EC policies via renovate: https://github.com/konflux-ci/konflux-ci/issues/2942

chore: update conforma policies

---

dependencies/pipelines-as-code/custom-console-patch.yaml

'Namespace' link in PRs detail is broken. This should fix.
Example PR: https://github.com/konflux-ci/namespace-lister/pull/154/checks
Actual value in Namespace Field: https://detailurl.setting.custom-console-url-namespace.is.not.configured/

add custom-console-url-namespace

---

dependencies/cert-manager/kustomization.yml
dependencies/kyverno/kustomization.yaml
dependencies/pipelines-as-code/kustomization.yml
dependencies/tekton-operator/kustomization.yml
dependencies/tekton-results/kustomization.yml
renovate.json

Adding kyverno, cert-manager and pipelines-as-code to be tracked with Renovate. Disabling cert-manager updates until we introduce Helm and then we can track trust-manager as well.
Closes: #1435

chore: track some github release with renovate
