konflux-ci/konflux-ci

.github/workflows/sanity-test.yml
dependencies/kustomization.yml
dependencies/pipelines-as-code/kustomization.yml
wait-for-all-deployments.sh

In addition verify that deployments of dependencies are ready.

Deploy pipelines-as-code

---

.github/workflows/sanity-test.yml
dependencies/tekton-config/kustomization.yml
dependencies/tekton-config/tekton-config.yml
dependencies/tekton-operator/kustomization.yml
dependencies/tekton-pipelines/kustomization.yml

The operator install pipelines, chains and triggers.

Install Tekton components using an operator

---

dependencies/tekton-results/certificate.yaml
dependencies/tekton-results/kustomization.yml
deploy-deps.sh
deploy-konflux.sh
konflux-ci/rbac/core/rbac.yaml
konflux-ci/ui/core/proxy/nginx.conf
test/resources/pipelines/dummy-pipeline.yaml

- Deploy Tekton Results
- Update the proxy to forward requests
- Update the RBAC to allow a user to fetch pods and logs (the UI requires it).
- Add a dummy pipeline for testing the changes above.

Deploy Tekton Results

---

README.md
konflux-ci/release/core/kustomization.yaml
konflux-ci/release/core/release-service-config.yaml
test/resources/demo-users/user/managed-ns1/ec-policy.yaml
test/resources/demo-users/user/managed-ns1/kustomization.yaml
test/resources/demo-users/user/managed-ns1/ns.yaml
test/resources/demo-users/user/managed-ns1/pvc.yaml
test/resources/demo-users/user/managed-ns1/role-binding.yaml
test/resources/demo-users/user/managed-ns1/rpa.yaml
test/resources/demo-users/user/ns1/kustomization.yaml
test/resources/demo-users/user/ns1/release-plan.yaml

Complete missing release resources and manifests for testing a release.

Complete missing release resources

---

deploy-deps.sh

Even when using "apply", we see in the CI that the command fails because the config already exists (on a fresh kind cluster). Add retries for handing it.

Retry the deployment of tekton config

---

.github/workflows/sanity-test.yml
deploy-konflux.sh
konflux-ci/ui/core/kustomization.yaml

Their repositories were modified to be public again.

Don't use pull secret for the UI images

---

README.md
deploy-deps.sh
deploy-konflux.sh
deploy-test-resources.sh
wait-for-all.sh

See the different commits for the improvements added for the deployment.

Better deployment

---

README.md
konflux-ci/rbac/core/tekton-chains.yaml

Automate the creation of tekton chains signing secrets

Automate the creation of tekton chains signing secrets

---

konflux-ci/ui/core/proxy/proxy.yaml

This will have to change later on.

chore: take ws manager image from rhtap-o11y-tenant

---

README.md
smee/smee-client.yaml
test/resources/demo-users/user/ns2/application-and-component.yaml
test/resources/demo-users/user/ns2/pull-request.yaml
test/resources/demo-users/user/ns2/rbac.yaml

Adding documentation for triggering builds via webhooks. Adding and tweaking some other sections to support that.

chore(RHTAPWATCH-946): document triggering via webhooks

---

.github/workflows/release.yml

Create Git release with changelog and assets
using Github CLI
Jira-Url: https://issues.redhat.com/browse/RHTAPWATCH-978

chore(RHTAPWATCH-978): Create git release

---

dependencies/registry/kustomization.yml
dependencies/registry/registry.yaml
deploy-deps.sh

- add internal registry resource to konflux
- update dependencies script

chore(RHTAPWATCH-1003): add internal registry

---

README.md
smee/smee-client.yaml
test/resources/demo-users/user/ns2/application-and-component.yaml

Document a demo workflow intended to be as streamlined as possible.
Closes #48 
Closes #47 
Closes #43

doc(RHTAPWATCH-1007): demo workflow

---

dependencies/ingress-nginx/kustomization.yml
deploy-deps.sh
kind-config.yaml

We don't use it, so stop deploying it.

Don't deploy ingress controller

---

README.md

Adding troubleshooting steps for dealing with issues with the GitHub app

doc: troubleshooting github secret creation

---

README.md
RELEASE.md

Document the process of creating a release.

doc: add RELEASE.md

---

deploy-deps.sh

Verify software requirements in beginning of deployment scripts

---

deploy-deps.sh

The tekton operator seems to overwrite whatever tekton configs that are in place when it is deployed. For that reason, we should wait for those configs to appear before deploying our own configs.

fix: tekton operator overwrites configs

---

konflux-ci/ui/core/kustomization.yaml

The new images provide the new Konflux UI.

Update UI images

---

test/resources/demo-users/user/ns1/rbac.yaml

This will allow to demonstrate the workspace switcher when using user2.

Give user2 access to ns1

---

README.md
dependencies/registry/registry.yaml

use default port for local registry

---

README.md

Added three suggestions on the README based on my experience while playing with the repo

Add suggestions to README

---

konflux-ci/integration/core/batch_v1_cronjob_integration-service-snapshot-garbage-collector.yaml

chore: reduce resource requests for snapshotgc

---

deploy-deps.sh

Changing the implementation of the retry function so it takes the command to retry and the error message to print if retry fails.

chore: print reason on retry failure

---

deploy-image-controller.sh

- Run the deployment before creating a secret
- Modify retry
Fix #110

Run image-controller deployment before creating a secret

---

konflux-ci/build-service/build-pipeline-config.yaml

The new bundles contain the git-clone and init tasks with public images.

Update build config-map

---

test/resources/demo-users/user/managed-ns1/appstudio-pipeline-sa.yaml
test/resources/demo-users/user/managed-ns1/kustomization.yaml
test/resources/demo-users/user/managed-ns1/role-binding.yaml
test/resources/demo-users/user/managed-ns1/rpa.yaml
test/resources/demo-users/user/managed-ns2/appstudio-pipeline-sa.yaml
test/resources/demo-users/user/managed-ns2/kustomization.yaml
test/resources/demo-users/user/managed-ns2/role-binding.yaml
test/resources/demo-users/user/managed-ns2/rpa.yaml
test/resources/demo-users/user/ns1/appstudio-pipeline-sa.yaml
test/resources/demo-users/user/ns1/kustomization.yaml

- Create the service account
- Update rolebindings with the new service account
- Update the RPA with the new service account
- Update kustomization files
fix #118

Use "appstudio-pipeline" service account for release

---

README.md

Add minimum and recommended requirements

Add minimum and recommended requirements

---

deploy-deps.sh

Increase wait timeout for `keyclock` and `cert-manager` by 1 minute
fix #75

Increase wait timeout for keyclock and cert-manager

---

README.md
test/resources/demo-users/user/ns2/integration-test-hello.yaml

Document the process of adding a customized integration test.
closes: #131

doc: add custom integration tests

---

README.md
docs/troubleshooting.md

The pac namespace includes multiple pods. mention the specific one that should be checked when troubleshooting.

doc: mention the specific pod for which pac logs should be collected

---

.github/workflows/differential-shellcheck.yaml
deploy-deps.sh

Using Github actions write shellcheck to run on
all the shell scripts.
Jira-Url: https://issues.redhat.com/browse/RHTAPWATCH-1044

chore(RHTAPWATCH-1044): Run shellcheck on shell scripts

---

dependencies/keycloak/deployment/configure-keycloak.yaml
test/resources/demo-users/user/managed-ns1/kustomization.yaml
test/resources/demo-users/user/managed-ns1/ns.yaml
test/resources/demo-users/user/managed-ns1/rbac.yaml
test/resources/demo-users/user/managed-ns2/kustomization.yaml
test/resources/demo-users/user/managed-ns2/ns.yaml
test/resources/demo-users/user/managed-ns2/rbac.yaml

- eases debugging of managed pipelines

enable access to managed workspaces

---

konflux-ci/release/core/apiextensions.k8s.io_v1_customresourcedefinition_releaseplans.appstudio.redhat.com.yaml
konflux-ci/release/core/apps_v1_deployment_release-service-controller-manager.yaml
test/resources/demo-users/user/ns1/rbac.yaml
test/resources/demo-users/user/ns1/release-plan.yaml
test/resources/demo-users/user/ns2/rbac.yaml

* release service update
* rbac and resources needed.

enable tenant release pipelines

---

README.md

doc: minor fixes in release documentation

---

docs/troubleshooting.md

Add instructions for restarting the container on which the cluster runs.

doc: restarting the cluster

---

README.md
docs/github-secrets.md
docs/quay.md
docs/troubleshooting.md

The documentation has many steps. To distinguish between explanations and actions that need to be done, we should use directive language and add some visual aids to help the reader focus on required steps.
closes: #157
closes: #159

doc: use directive language

---

konflux-ci/release/core/apps_v1_deployment_release-service-controller-manager.yaml
konflux-ci/release/core/batch_v1_cronjob_remove-expired-releases.yaml

Migrate release-service quay references to the konflux-ci org.

refactor(RELEASE-977): migrate release-service quay org

---

.github/.kube-linter-config.yaml
.github/workflows/kube-linter.yaml

Running Kubelinter on Konflux-ci

chore(RHTAPWATCH-1043): run Kubelinter on Konflux-ci

---

.gitignore
pkg/konftool/gh_app/templates/another.gohtml
pkg/konftool/gh_app/templates/embed.go
pkg/konftool/gh_app/templates/gh_app.gohtml
pkg/konftool/gh_app/web.go
pkg/konftool/web/echo.go
pkg/konftool/web/renderer.go
pkg/konftool/webapps/echolike.go
pkg/konftool/webapps/templateloader.go

Some more basic infrstructure for writing the konftool web UI.

konftool:web: Apps and Templates

---

README.md

We got user feedback saying it's unclear whether the PR created on their test repo should be merged or not once it's created. This change clarifies that.
closes: #154

doc: user should not merge the pr too soon

---

CONTRIBUTING.md

update contributing.md with kubelinter

chore(RHTAPWATCH-1101): update contributing.md with kubelinter

---

konflux-ci/ui/core/proxy/logout.html

Show the email of the user in the test html page.

Show the email of the user

---

.github/.kube-linter-config.yaml
dependencies/keycloak/deployment/db.yaml
dependencies/keycloak/deployment/kustomization.yml
dependencies/pipelines-as-code/kustomization.yml
dependencies/pre-deployment-pvc-binding/pre-deployment-pvc-binding.yaml
dependencies/registry/registry.yaml
dependencies/tekton-operator/kustomization.yml
dependencies/tekton-results/kustomization.yml
konflux-ci/rbac/core/tekton-chains.yaml

Fix Kubelinter issues in Konflux ci.
This will be done by removing checks out of the excluded checks and solve them one by one

chore(RHTAPWATCH-1043): fix kubelinter root-related issues

---

renovate.json

Automerge and approve update PRs of Konflux
core services produced by renovate.

Automerge/Approve renovate PRs

---

test/e2e/vars.sh

fixes https://github.com/konflux-ci/konflux-ci/issues/252

fix: e2e: create unique Component names

---

.github/workflows/sanity-test.yml

For easier debugging, collect logs files.

Collect logs files

---

konflux-ci/enterprise-contract/core/kustomization.yaml
test/resources/demo-users/user/managed-ns2/rpa.yaml

Update the RPA to a newer git reference in which all tasks support the use of self-signed certificates.

feat: use release pipeline supporting custom ca

---

README.md

With all tasks and processes supporting working with registries with
self-signed CA certificates, we can now convert the "no UI" flow to
use an in-cluster registry end to end.

doc(RHTAPWATCH-1173): use local registry end to end

---

deploy-deps.sh

Retry pre-deployment PVC Binding

---

README.md
dependencies/cert-manager/self-signed-cluster-issuer.yaml
dependencies/cluster-issuer/self-signed-cluster-issuer.yaml
dependencies/registry/certificate.yaml
dependencies/registry/kustomization.yml
dependencies/registry/registry.yaml
dependencies/registry/trust-bundle.yaml
dependencies/tekton-config/tekton-config.yml
dependencies/trust-manager/kustomization.yml
dependencies/trust-manager/trust-manager.yaml
deploy-deps.sh
konflux-ci/build-service/core/kustomization.yaml
konflux-ci/build-service/core/mount-custom-ca-bundle.yaml
konflux-ci/enterprise-contract/core/kustomization.yaml
test/e2e/customize-docker-pipeline.sh
test/e2e/vars.sh
test/resources/demo-users/user/managed-ns2/appstudio-pipeline-sa.yaml
test/resources/demo-users/user/managed-ns2/rpa.yaml
test/resources/demo-users/user/ns2/appstudio-pipeline-sa.yaml
test/resources/demo-users/user/ns2/ec-integration-test.yaml

This PR merges the local-registry feature branch into the main branch. Once this is merged, users can use the local registry end to end.

Local registry

---

konflux-ci/ui/core/kustomization.yaml
renovate.json

Also enabling the kustomize manager

chore(KFLUXBUGS-1564): use renovate to maintain ws-manager version

---

konflux-ci/build-service/core/build-pipeline-config.yaml
renovate.json

chore(KFLUXBUGS-1565): configure renovate for build-pipeline-config

---

renovate.json

Automatically merge renovate changes for quay.io/konflux-ci repos

chore: enable automerge for quay.io/konflux-ci

---

renovate.json

chore: add packages to renovate automerge

---

docs/quay.md

update link in quay documentation

update link in quay documentation

---

deploy-konflux.sh

Add information for successful deployment
Dump error log in case of deployment failure
#171

Dump information at the end of deploy-konflux.sh

---

README.md

Specify minimum software versions for deploying on kind
Closes: #39

docs(KONFLUX-5768): minimum software versions

---

.github/workflows/sanity-test.yml

Closes https://github.com/konflux-ci/konflux-ci/issues/1111

fix: update sanity test prereqs check

---

deploy-konflux.sh
konflux-ci/namespace-lister/deployment.yaml
konflux-ci/namespace-lister/kustomization.yaml
konflux-ci/namespace-lister/namespace.yaml
konflux-ci/namespace-lister/network_policy.yaml
konflux-ci/namespace-lister/patches/with-header-auth-email.yaml
konflux-ci/namespace-lister/rbac.yaml
konflux-ci/namespace-lister/service.yaml
konflux-ci/ui/core/proxy/nginx.conf

add namespace-lister

---

renovate.json

https://issues.redhat.com/browse/KFLUXDP-18
Tested the configuration in [my fork of konflux-ci repo](https://github.com/psturc-org/konflux-ci/pull/20)

feat: renovate: auto-update E2E test image

---

konflux-ci/rbac/core/rbac.yaml

update konflux-admin-user-actions for namespace-lister

---

dependencies/dex/dex.yaml
dependencies/dex/kustomization.yml

Track Dex updates using renovate.
Closes: #1142

chore(KONFLUX-6528): update dex with renovate

---

konflux-ci/namespace-lister/certificate.yaml
konflux-ci/namespace-lister/deployment.yaml
konflux-ci/namespace-lister/kustomization.yaml
konflux-ci/ui/core/proxy/nginx.conf

add TLS support in namespace-lister

---

konflux-ci/namespace-lister/kustomization.yaml

bump namespace lister

---

konflux-ci/namespace-lister/deployment.yaml
konflux-ci/namespace-lister/kustomization.yaml

update namespace-lister image name to be renovate friendly

---

dependencies/tekton-operator/kustomization.yml
dependencies/tekton-results/kustomization.yml

update tekton version

---

test/resources/demo-users/user/managed-ns1/rpa.yaml
test/resources/demo-users/user/managed-ns2/rpa.yaml

chore: update rpa release pipeline ref

---

konflux-ci/build-service/core/build-pipeline-config.yaml

add tekton-bundle-builder pipeline to build configmap

add tekton-bundle-builder pipeline to build configmap

---

test/e2e/customize-docker-pipeline.sh
test/e2e/run-e2e.sh
test/e2e/vars.sh

closes https://github.com/konflux-ci/konflux-ci/issues/812
depends on https://github.com/konflux-ci/e2e-tests/pull/1550 (should be merged after that one is in)

test: validate docker-build-oci-ta pipelines

---

dependencies/smee/smee-client.yaml

Adding livenessProbe as part of https://issues.redhat.com/browse/SPRE-1255

adding livenessProbe for smee-client

---

konflux-ci/build-service/core/build-pipeline-config.yaml

Add tekton-bundle-builder-oci-ta pipeline to build configmap

chore(KFLUXVNGD-240): add tekton-bundle-builder-oci-ta to config

---

dependencies/smee/smee-client.yaml

Based on the conversation on https://issues.redhat.com/browse/SPRE-1255 we will be removing the livenessProbe since is not meeting the expectations

removing livenessProbe

---

renovate.json

Also reorder auto-merged pacakges alphabetically.

chore: auto-merge gosmee updates

---

konflux-ci/enterprise-contract/policies/enterprise-contract-service_appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_all.yaml
konflux-ci/enterprise-contract/policies/enterprise-contract-service_appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_default.yaml
konflux-ci/enterprise-contract/policies/enterprise-contract-service_appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_redhat-no-hermetic.yaml
konflux-ci/enterprise-contract/policies/enterprise-contract-service_appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_redhat-trusted-tasks.yaml
konflux-ci/enterprise-contract/policies/enterprise-contract-service_appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_redhat.yaml
konflux-ci/enterprise-contract/policies/enterprise-contract-service_appstudio.redhat.com_v1alpha1_enterprisecontractpolicy_slsa3.yaml
renovate.json

chore: track conforma policies with renovate

---

.github/workflows/suggest_docs.yml
scripts/suggest_docs.py

I've been asked to add the upstream-docs-enhancer tool to the konflux-ci project and to test it while Paul and I are writing Konflux documentation to see if it helps us identify, write, and update the documentation based on code changes within the konflux-ci repository. The goal is to produce up-to-date documentation as quickly as possible and ensure the content stays up-to-date.

Add upstream-docs-enhancer to the project.
